mctpd: standalone-build: Update gtest to v1.11.0
F32 is no longer supported. After updating container used in CI for
standalone builds to F34, googletest fails with:

googletest/googletest/src/gtest-death-test.cc:1301:24: error: 'dummy' may be used uninitialized [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

Let's update gtest to use the latest release version.

Tested: No code changes.

Change-Id: I886221bcf76ae6ead7cf35d144d0fa8886f616de
Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>