mctpd: Fix 'linker' input unused
error: -lstdc++fs: 'linker' input unused
[-Werror,-Wunused-command-line-argument].

Tested: No functional change. Code compiles without
unused-command-line-argument warnings.

Change-Id: I067944c4a23fc62393ee725caf92f5db362f7f24
Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>